# Generated by Django 2.2.2 on 2019-06-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(upload_to='media/%Y/%m/%d')),
                ('stream', models.CharField(choices=[('ANE', 'Aeronautical Engineering'), ('AGR', 'Agricultural Engineering'), ('AUT', 'Automobile Engineering'), ('BIO', 'Bio-Technology'), ('CHE', 'Chemical Engineering'), ('CIV', 'Civil Engineering'), ('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('INF', 'Information Technology'), ('MEC', 'Mechanical Engineering')], max_length=20)),
            ],
        ),
    ]
